---
apiVersion: v1
kind: Pod
metadata:
  name: centos
  namespace: dev
  labels:
    app: centos
spec:
  containers:
  - name: centos
    image: centos:latest
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do curl -m5 http://nginx-svc; sleep 3; done;" ]
    resources: {}