apiVersion: projectcalico.org/v3
kind: GlobalReport
metadata:
  name: cluster-policy-audit
spec:
  reportType: policy-audit
  # schedule examples:
  ## every top of hour: 0 * * * *
  ## every 5 min: */5 * * * *
  schedule: '0 */12 * * *'