apiVersion: v1
kind: Pod
metadata:
  name: run-reporter-custom
  namespace: tigera-compliance
  labels:
    k8s-app: compliance-reporter
spec:
  nodeSelector:
    beta.kubernetes.io/os: linux
  restartPolicy: OnFailure
  serviceAccount: tigera-compliance-reporter
  serviceAccountName: tigera-compliance-reporter
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  imagePullSecrets:
    - name: tigera-pull-secret
  containers:
  - name: reporter
    # Modify this image name, if you have re-tagged the image and are using a local
    # docker image repository.
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    image: quay.io/tigera/compliance-reporter:v3.5.0
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    env:
      # Modify this value with name of an existing globalreport resource.
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: TIGERA_COMPLIANCE_REPORT_NAME
      value: hourly-cluster-networkacess
      # Modify these values with the start and end time frame that should be reported on.
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # - name: TIGERA_COMPLIANCE_REPORT_START_TIME
    #   value: "2020-08-19T15:20:00Z"
    # - name: TIGERA_COMPLIANCE_REPORT_END_TIME
    #   value: "2020-08-19T15:35:00Z"
    - name: TIGERA_COMPLIANCE_JOB_START_DELAY
      value: "5m"
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: LOG_LEVEL
      value: "warning"
    - name: ELASTIC_INDEX_SUFFIX
      value: cluster
    - name: ELASTIC_SCHEME
      value: https
    - name: ELASTIC_HOST
      value: tigera-secure-es-http.tigera-elasticsearch.svc
    - name: ELASTIC_PORT
      value: "9200"
    - name: ELASTIC_USER
      valueFrom:
        secretKeyRef:
          name: tigera-ee-compliance-reporter-elasticsearch-access
          key: username
          optional: true
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: tigera-ee-compliance-reporter-elasticsearch-access
          key: password
          optional: true
    - name: ELASTIC_SSL_VERIFY
      value: "true"
    - name: ELASTIC_CA
      value: /etc/ssl/elastic/ca.pem
    volumeMounts:
    - mountPath: /var/log/calico
      name: var-log-calico
    - name: elastic-ca-cert-volume
      mountPath: /etc/ssl/elastic/
    - name: tigera-compliance-reporter-token
      mountPath: /var/run/secrets/kubernetes.io/serviceaccount
    livenessProbe:
      httpGet:
        path: /liveness
        port: 9099
        host: localhost
  volumes:
  - name: var-log-calico 
    hostPath:
      path: /var/log/calico
      type: DirectoryOrCreate
  - name: elastic-ca-cert-volume
    secret:
      optional: true
      items:
      - key: tls.crt
        path: ca.pem
      secretName: tigera-secure-es-http-certs-public
  - name: tigera-compliance-reporter-token
    secret:
      defaultMode: 420
      secretName: <COMPLIANCE_REPORTER_TOKEN>
