apiVersion: projectcalico.org/v3
kind: GlobalReport
metadata:
  name: demo-networkaccess
  labels:
    deployment: pre-prod
spec:
  reportType: network-access
  endpoints:
    namespaces:
      names: ["dev","uat"]
  ## every top of hour: 0 * * * *
  ## every 5 min: */5 * * * *
  ## every 6 hours: 0 */6 * * *
  schedule: '0 */8 * * *'