# alert template to quickly create similar alerts
apiVersion: projectcalico.org/v3
kind: GlobalAlertTemplate
metadata:
  name: dns.restricted-dns-access
spec:
  description: "Pod attempted to access restricted domain"
  summary: "[dns] pod ${client_namespace}/${client_name_aggr} attempted to access '${qname}'"
  severity: 100
  dataSet: flows
  period: 5m
  lookback: 5m
  query: '(qname = "put.restricted.domain.com" OR qname = "restricted.domain.com")'
  aggregateBy: [client_namespace, client_name_aggr, qname]
  metric: count
  condition: gt
  threshold: 0
---

apiVersion: projectcalico.org/v3
kind: GlobalAlert
metadata:
  name: dns.apple-access
spec:
  description: "Pod attempted to access apple.com domain"
  summary: "[dns] pod ${client_namespace}/${client_name_aggr} attempted to access '${qname}'"
  severity: 100
  dataSet: dns
  period: 1m
  lookback: 5m
  query: '(qname = "www.apple.com" OR qname = "apple.com")'
  aggregateBy: [client_namespace, client_name_aggr, qname]
  metric: count
  condition: gt
  threshold: 0
---