---
apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  namespace: ns2
  labels:
    app: netshoot
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot:latest
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do curl http://nginx-svc; sleep 3; done;" ]
    resources: {}